[package]
name = "tutor-nodb"
version = "0.1.0"
authors = ["prestone"]
edition = "2024"
default-run = "tutor-service"

[dependencies]
actix-web = "4.11.0"
actix-rt = "2.11.0"

[[bin]]
name = "basic-server"  # Name of the binary

[[bin]]
name = "tutor-service"